### ISSUE TITLE
NextCloud 19 Not loading .fbx files using Files 3D 3.1.0

### ISSUE THREAD

**Issue by JesseMader** [v1r0x/files_3d#20] opened 2020-08-20 21:26 UTC
As soon as I saw this app I had to try it out. Installed fine from NC but when trying to click on one of my teams .fbx files it downloaded it instead of previewing it. Disabling it and enabling it was able to get around this issue. Now the issue I am experiencing is with the preview itself. Below is what I am presented while within files when opening a .fbx file. 

![image](https://user-images.githubusercontent.com/42048537/90827213-de2e2b80-e309-11ea-8f31-b5ef7d855809.png)

Any Idea as to why this is occurring?

**Edit:** Forgot to include steps taken to get this result.

**Steps Taken:**
1. Open NextCloud
2. Go to Apps
3. Search for Files 3D
4. Download and Enable
a. Disable, Refresh, Enable Files 3D
5. Locate .fbx file and open
6. The preview window opens but does not display the model

**Expected Results:**
Model preview is displayed

**Current Results:**
Model is not displayed and loads only the frame (see screenshot above)

**Troubleshooting:**
- Opened in https://threejs.org/editor/ without issue.
- File loads fine outside of NC
- Redownloaded Files 3D twice
- Cleared Cache

**Comment by XChrissX** [comment] 2020-08-20 22:06
Habe das gleiche Problem.

**Comment by v1r0x** [comment] 2020-08-22 07:20
Duplicate of #19

**Closed as completed by v1r0x** 2020-08-22 07:20 UTC

**Comment by v1r0x** [comment] 2020-09-08 15:28
Please check new 0.3.2 version and update in #19
