### ISSUE TITLE
Nextcloud 17 support

### ISSUE THREAD

**Issue by JonathanTreffler** [v1r0x/files_3d#6] opened 2019-11-17 10:12 UTC
Is this app compatible to Nextcloud 17 ?
If yes , when will appinfo/info.xml be changed ?

**Comment by v1r0x** [comment] 2020-01-21 15:32
Hey @TessyPowder  
Unfortunately, this is app is currently unmaintained.

The problem is that most of 3d files do not set a (correct) mime-type and thus are not supported. And some file types do not have a mime-type at all. The new (since nc 16) viewer plugin of nc only allows to register mime-types, but not file extensions (see #4) to register an external app to show the file content.
As long as there is no solution to this, I won't put more work into this, because the current workaround (for pre nc16) is not very stable but error prone. Sorry!

I'll close this issue, because there is a similar issue (#7) for the more recent nc 18 release

**Closed as completed by v1r0x** 2020-01-21 15:32 UTC
